"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import Image from "next/image";
import {ArrowUpRight,ArrowRight,MapPin,Clock,Scissors,Check,Instagram,MessageCircle} from "lucide-react";
import {db,rpc} from "@/lib/db";
import {defaults,Settings,Hours,days,money,dayKey,pretty,time,shift} from "@/lib/model";

export default function Home(){
 const [s,setS]=useState<Settings>(defaults),[hours,setHours]=useState<Hours[]>([]);
 const [date,setDate]=useState(""),[slot,setSlot]=useState(""),[slots,setSlots]=useState<string[]>([]);
 const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(""),[receipt,setReceipt]=useState("");
 const [person,setPerson]=useState({first:"",last:"",phone:"",website:""});
 useEffect(()=>{if(!db)return;Promise.all([db.from("business_settings").select("*").single(),db.from("business_hours").select("*").order("id")]).then(([a,b])=>{if(a.error||b.error){setError("No pudimos cargar la disponibilidad. Intentá más tarde.");return;}setS(a.data);setHours(b.data??[]);});setDate(dayKey());},[]);
 useEffect(()=>{let active=true;setSlot("");setSlots([]);if(!date||!s.enabled)return;setBusy(true);rpc<{starts_at:string}[]>("available_slots",{p_day:date}).then(r=>{if(active)setSlots(r.map(x=>x.starts_at));}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[date,s.enabled]);
 async function book(){setError("");if(person.website)return;setBusy(true);try{const id=await rpc<string>("book_appointment",{p_start:slot,p_first:person.first.trim(),p_last:person.last.trim(),p_phone:person.phone,p_price:s.price});setReceipt(id);setStep(4);}catch(e){setError(e instanceof Error?e.message:"No pudimos reservar.");setStep(1);setSlots([]);try{setSlots((await rpc<{starts_at:string}[]>("available_slots",{p_day:date})).map(x=>x.starts_at));}catch{}}finally{setBusy(false);}}
 const wa="https://wa.me/"+s.whatsapp.replace(/\D/g,"");
 return <><header className="public-header container"><Link href="/" className="brand">{s.logo?<Image src={s.logo} alt="Logo TT Peluquería" width={48} height={48} unoptimized/>:<span className="monogram">TT</span>}<span>TT<span className="brand-small">PELUQUERÍA</span></span></Link><nav><a href="#nosotros">El lugar</a><a href="#ubicacion">Encontranos</a><a className="button small" href="#reservar">Reservar turno <ArrowUpRight size={16}/></a></nav></header>
 <main><section className="hero container"><div><p className="eyebrow"><span className="dot"/> ROJAS, BUENOS AIRES</p><h1>Tu estilo.<br/>Tu momento.<br/><em>Tu próximo corte.</em></h1><p className="hero-copy">Un buen corte hace la diferencia. Atención personalizada, detalles que importan y un turno que se adapta a vos.</p><a className="button" href="#reservar">Reservá tu lugar <ArrowUpRight size={20}/></a><p className="muted mini">Elegí el día y la hora. Así de simple.</p></div><div className="hero-art">{s.photos[0]?<Image src={s.photos[0]} alt="TT Peluquería" fill unoptimized sizes="(max-width: 800px) 100vw, 50vw"/>:<><div className="art-lines"/><Scissors size={150} strokeWidth={.7}/><span className="art-type">EL CORTE<br/>QUE VA<br/>CON VOS.</span></>}<span className="art-caption">TT PELUQUERÍA <span>SOLO CORTES. TODO EL ESTILO.</span></span></div></section>
 <div className="ticker"><span>CORTES DE PELO</span><span>✦</span><span>ATENCIÓN CON TURNO</span><span>✦</span><span>HECHO A TU ESTILO</span><span>✦</span><span>TT PELUQUERÍA</span></div>
 <section className="container section booking-layout" id="reservar"><div><p className="eyebrow">TU PRÓXIMO TURNO</p><h2>Un corte.<br/>Cero vueltas.</h2><p className="muted">Reservá desde donde estés, en unos pocos pasos.</p><div className="service"><Scissors/><div><h3>Corte de pelo</h3><span className="muted"><Clock size={14}/> {s.duration} minutos aprox.</span></div><strong>{s.price>0?money(s.price):"A confirmar"}</strong></div><p className="muted mini">El pago se realiza en la peluquería al terminar tu corte.</p></div>
 <div className="card booking"><div className="steps">{["Fecha y hora","Tus datos","Confirmación"].map((x,i)=><span key={x} className={step>=i+1?"active":""}><b>{step>i+1?<Check size={14}/>:i+1}</b>{x}</span>)}</div>
 {!s.enabled?<div className="empty"><Clock/><h3>Estamos preparando la agenda online</h3><p>Por ahora, coordiná tu turno por WhatsApp.</p><a className="button" href={wa}>Consultar disponibilidad</a></div>:<>
 {step===1&&<><h3>¿Cuándo te vemos?</h3><label>Elegí una fecha<input type="date" value={date} min={dayKey()} max={shift(dayKey(),90)} onChange={e=>{setDate(e.target.value);setError("");}}/></label><label>Horarios disponibles</label><div className="slots">{slots.map(x=><button key={x} className={slot===x?"selected":"secondary"} onClick={()=>setSlot(x)}>{time(x)}</button>)}</div>{busy?<p>Cargando horarios…</p>:slots.length===0?<p className="muted">No hay horarios disponibles para esta fecha. Probá otro día.</p>:null}<button className="wide" disabled={!slot||busy} onClick={()=>setStep(2)}>Continuar <ArrowRight size={17}/></button></>}
 {step===2&&<form onSubmit={e=>{e.preventDefault();setStep(3);}}><h3>Contanos quién viene</h3><div className="form-grid"><label>Nombre<input autoComplete="given-name" required minLength={2} maxLength={60} value={person.first} onChange={e=>setPerson({...person,first:e.target.value})}/></label><label>Apellido<input autoComplete="family-name" required minLength={2} maxLength={60} value={person.last} onChange={e=>setPerson({...person,last:e.target.value})}/></label></div><label>Teléfono con código de área<input type="tel" autoComplete="tel" required pattern="[+0-9 ()-]{10,22}" placeholder="2474 472816" value={person.phone} onChange={e=>setPerson({...person,phone:e.target.value})}/></label><input aria-hidden="true" tabIndex={-1} className="honeypot" autoComplete="off" value={person.website} onChange={e=>setPerson({...person,website:e.target.value})}/><p className="mini muted">Usamos tus datos para gestionar tu turno y comunicarnos con vos por esa reserva.</p><div className="actions"><button type="button" className="secondary" onClick={()=>setStep(1)}>Volver</button><button>Revisar turno <ArrowRight size={16}/></button></div></form>}
 {step===3&&<><h3>Todo listo para tu corte</h3><div className="receipt"><p>Corte de pelo <strong>{money(s.price)}</strong></p><p>Fecha <strong>{pretty(date)}</strong></p><p>Hora <strong>{time(slot)}</strong></p><p>Cliente <strong>{person.first} {person.last}</strong></p><p>Teléfono <strong>{person.phone}</strong></p></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>setStep(2)}>Volver</button><button disabled={busy} onClick={book}>{busy?"Reservando…":"Confirmar turno"}</button></div></>}
 {step===4&&<div className="empty"><span className="success-icon"><Check/></span><h3>¡Tu turno está reservado!</h3><p>{pretty(date)} · {time(slot)}</p><p>Corte de pelo · {money(s.price)}</p><p className="mini muted">Referencia: {receipt}</p><p>Guardá esta confirmación. Si necesitás cambiar el turno, escribinos.</p><a className="button secondary" href={wa+"?text="+encodeURIComponent("Hola, consulto por mi turno "+receipt)}>Contactar a la peluquería</a></div>}</>}
 {error&&<p className="alert" role="alert">{error}</p>}</div></section>
 <section className="container section" id="nosotros"><p className="eyebrow">TT PELUQUERÍA</p><div className="section-title"><h2>El detalle está<br/>en el corte.</h2><p className="muted">Un espacio para renovar tu look,<br/>con el tiempo y la atención que merecés.</p></div>{s.photos.length>0?<div className="gallery">{s.photos.map((x,i)=><div key={i}><Image src={x} alt={"El lugar y nuestros cortes "+(i+1)} fill unoptimized sizes="(max-width: 700px) 100vw, 33vw"/></div>)}</div>:<a className="instagram-card" href={s.instagram} target="_blank" rel="noreferrer"><Instagram size={32}/><div><h3>Conocé nuestros cortes</h3><p>Inspirate con nuestros trabajos en Instagram.</p></div><ArrowUpRight/></a>}</section>
 <section className="location section" id="ubicacion"><div className="container two"><div><p className="eyebrow">NOS VEMOS ACÁ</p><h2>Tu peluquería<br/>en Rojas.</h2><p><MapPin size={18}/> {s.address}</p><a className="button secondary" target="_blank" rel="noreferrer" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(s.address)}>Cómo llegar <ArrowUpRight size={18}/></a></div><div className="card"><h3><Clock size={20}/> Horarios de atención</h3>{hours.some(h=>!h.closed)?hours.map(h=><div className="hours-row" key={h.id}><span>{days[h.id]}</span><strong>{h.closed?"Cerrado":h.opens.slice(0,5)+" — "+h.closes.slice(0,5)}</strong></div>):<p>Martes a sábado, solo con turno.<br/>Lunes y domingo cerrado.</p>}<a href={wa} className="contact"><MessageCircle size={18}/> Consultanos por WhatsApp</a></div></div></section></main>
 <footer className="container"><span>TT PELUQUERÍA · ROJAS</span><div><a href={s.instagram}>Instagram</a><a href={wa}>WhatsApp</a><Link href="/admin">Administración</Link></div></footer></>;
}
