"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Bell,CalendarDays,LayoutDashboard,Wallet,Users,ChartNoAxesColumn,Settings2,History,LogOut,ArrowUpRight,Plus,Check} from "lucide-react";
import {db,rpc,all} from "@/lib/db";
import {Appointment,Block,Customer,defaults,Hours,methods,money,Notice,Payment,Settings,dayKey,days,pretty,shift,summarize,time} from "@/lib/model";
import Chart from "./Charts";

const tabs=[["Inicio",LayoutDashboard],["Agenda",CalendarDays],["Caja",Wallet],["Historial",History],["Clientes",Users],["Estadísticas",ChartNoAxesColumn],["Notificaciones",Bell],["Configuración",Settings2]] as const;
export default function Panel(){
 const [tab,setTab]=useState<string>("Inicio"),[a,setA]=useState<Appointment[]>([]),[p,setP]=useState<Payment[]>([]),[c,setC]=useState<Customer[]>([]),[n,setN]=useState<Notice[]>([]),[blocks,setBlocks]=useState<Block[]>([]);
 const [settings,setSettings]=useState<Settings>(defaults),[hours,setHours]=useState<Hours[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [date,setDate]=useState(dayKey()),[view,setView]=useState("Día"),[selected,setSelected]=useState<Appointment|null>(null),[customer,setCustomer]=useState<Customer|null>(null);
 const [search,setSearch]=useState(""),[from,setFrom]=useState(dayKey().slice(0,7)+"-01"),[to,setTo]=useState(dayKey()),[method,setMethod]=useState("");
 const load=useCallback(async()=>{try{const [aa,pp,cc,nn,bb,ss,hh]=await Promise.all([all<Appointment>("appointments"),all<Payment>("payments"),all<Customer>("customers"),all<Notice>("notifications"),all<Block>("blocked_times"),all<Settings>("business_settings"),all<Hours>("business_hours")]);setA(aa);setP(pp);setC(cc);setN(nn);setBlocks(bb);setSettings(ss[0]);setHours(hh);}catch(e){setError(e instanceof Error?e.message:"No pudimos cargar los datos.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();const id=setInterval(()=>void load(),15000);return()=>clearInterval(id);},[load]);
 async function action(action:string,data:Record<string,unknown>={}){setBusy(true);setError("");setMessage("");try{await rpc("admin_action",{p_action:action,p_data:data});setMessage("Cambios guardados.");await load();return true;}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.");return false;}finally{setBusy(false);}}
 const names=useMemo(()=>Object.fromEntries(c.map(x=>[x.id,x.first_name+" "+x.last_name])),[c]);
 const today=dayKey(),todayA=a.filter(x=>dayKey(x.starts_at)===today),todayP=summarize(p,today,today),monthP=summarize(p,today.slice(0,7)+"-01",today);
 const unread=n.filter(x=>!x.read_at).length;
 const range=summarize(p,from,to);
 const filtered=range.rows.filter(x=>(!method||x.method===method)&&x.customer_name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.paid_at.localeCompare(a.paid_at));
 const end=view==="Día"?date:view==="Semana"?shift(date,6):new Date(Number(date.slice(0,4)),Number(date.slice(5,7)),0).toISOString().slice(0,10);
 const start=view==="Mes"?date.slice(0,7)+"-01":date;
 const agenda=a.filter(x=>dayKey(x.starts_at)>=start&&dayKey(x.starts_at)<=end).sort((x,y)=>x.starts_at.localeCompare(y.starts_at));
 function period(v:string){const d=new Date(today+"T12:00:00Z");if(v==="Hoy"){setFrom(today);setTo(today);}if(v==="Ayer"){setFrom(shift(today,-1));setTo(shift(today,-1));}if(v==="Semana"){setFrom(shift(today,-((d.getUTCDay()+6)%7)));setTo(today);}if(v==="Mes"){setFrom(today.slice(0,7)+"-01");setTo(today);}if(v==="Anterior"){const last=shift(today.slice(0,7)+"-01",-1);setFrom(last.slice(0,7)+"-01");setTo(last);}}
 function group(rows:Payment[],key:(x:Payment)=>string,value:(x:Payment)=>number){const m:Record<string,number>={};rows.forEach(x=>{const k=key(x);m[k]=(m[k]??0)+value(x);});return Object.entries(m).sort(([a],[b])=>a.localeCompare(b)).map(([label,value])=>({label,value}));}
 const filters=<div className="filters"><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><label>Mes<input type="month" onChange={e=>{if(!e.target.value)return;setFrom(e.target.value+"-01");setTo(shift(e.target.value+"-01",new Date(Number(e.target.value.slice(0,4)),Number(e.target.value.slice(5,7)),0).getDate()-1));}}/></label></div>;
 function appointmentRow(x:Appointment){return <button className="appointment" key={x.id} onClick={()=>setSelected(x)}><strong>{time(x.starts_at)}</strong><span>{names[x.customer_id]}<small>Corte de pelo · {money(x.price)}</small></span><span className={"badge "+x.status.toLowerCase()}>{x.status}</span><ArrowUpRight size={16}/></button>;}
 const paymentTable=(rows:Payment[])=><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Hora de cobro</th><th>Cliente</th><th>Medio de pago</th><th>Importe</th><th>Turno</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{pretty(x.paid_at)}</td><td>{time(x.paid_at)}</td><td>{x.customer_name}</td><td>{x.method}</td><td>{money(x.amount)}</td><td><button className="text-button" onClick={()=>setSelected(a.find(y=>y.id===x.appointment_id)??null)}>Ver turno</button></td></tr>)}</tbody></table>{rows.length===0&&<p className="empty muted">No hay cobros en este período.</p>}</div>;
 return <div className="admin"><aside className="sidebar"><Link href="/" className="brand"><span className="monogram">TT</span><span>PELUQUERÍA<small>Administración</small></span></Link><p className="eyebrow">TU NEGOCIO</p><nav>{tabs.map(([name,Icon])=><button key={name} onClick={()=>{setTab(name);setSearch("");setMessage("");}} className={tab===name?"nav-item chosen":"nav-item"}><Icon size={19}/>{name}{name==="Notificaciones"&&unread>0&&<b className="counter">{unread}</b>}</button>)}</nav><div className="sidebar-bottom"><Link href="/" target="_blank">Ver página pública <ArrowUpRight size={15}/></Link><button className="nav-item" onClick={()=>void db?.auth.signOut()}><LogOut size={18}/> Cerrar sesión</button></div></aside>
 <div className="admin-body"><header className="admin-header"><span>TT Peluquería <span className="muted">/ {tab}</span></span><button className="secondary small" onClick={()=>void db?.auth.signOut()}>Salir</button><button className="notification-button secondary" aria-label={unread+" reservas nuevas"} onClick={()=>setTab("Notificaciones")}><Bell size={19}/>{unread>0&&<span className="counter">{unread}</span>}</button></header><main className="admin-content">
 <div className="section-title"><div><p className="eyebrow">{pretty(today)}</p><h1>{tab==="Inicio"?"Así va tu día.":tab}</h1><p className="muted">{tab==="Inicio"?"Tu agenda y los números de tu negocio, al día.":tab==="Caja"?"Ingresos registrados al realizar y cobrar cada corte.":""}</p></div>{tab==="Inicio"&&<button onClick={()=>{setTab("Agenda");setDate(today);}}>Ver agenda <ArrowUpRight size={17}/></button>}</div>
 {error&&<div className="alert" role="alert">{error}<button className="text-button" onClick={()=>setError("")}>Cerrar</button></div>}{message&&<p className="success" role="status"><Check size={16}/>{message}</p>}{loading?<p>Cargando tu negocio…</p>:<>
 {tab==="Inicio"&&<><div className="metrics"><Metric label="Generado hoy" value={money(todayP.total)} highlight/><Metric label="Turnos de hoy" value={todayA.length}/><Metric label="Realizados" value={todayA.filter(x=>x.status==="Realizado").length}/><Metric label="Pendientes" value={todayA.filter(x=>["Reservado","Confirmado"].includes(x.status)).length}/><Metric label="Cancelados" value={todayA.filter(x=>x.status==="Cancelado").length}/></div><div className="dashboard-grid"><section className="card"><div className="section-title"><h3>Agenda de hoy</h3><span className="badge">{todayA.length} turnos</span></div>{todayA.sort((a,b)=>a.starts_at.localeCompare(b.starts_at)).map(appointmentRow)}{!todayA.length&&<p className="empty muted">No tenés turnos para hoy.</p>}</section><section className="card monthly"><p className="eyebrow">ESTE MES</p><h2>{money(monthP.total)}</h2><p>generados en cortes cobrados</p><hr/><div className="receipt"><p>Cortes realizados <strong>{monthP.cuts}</strong></p><p>Clientes atendidos <strong>{monthP.customers}</strong></p><p>Promedio por día <strong>{money(monthP.total/Number(today.slice(8)))}</strong></p><p>Cortes por día <strong>{(monthP.cuts/Number(today.slice(8))).toFixed(1)}</strong></p></div><p className="mini">Promedios sobre días calendario transcurridos.</p></section></div>{unread>0&&<button className="notice-strip" onClick={()=>setTab("Notificaciones")}><Bell size={20}/>{unread} reservas nuevas para revisar <ArrowUpRight size={17}/></button>}</>}
 {tab==="Agenda"&&<><div className="toolbar"><input aria-label="Fecha de agenda" type="date" value={date} onChange={e=>setDate(e.target.value)}/><div className="segmented">{["Día","Semana","Mes"].map(v=><button className={view===v?"":"secondary"} key={v} onClick={()=>setView(v)}>{v}</button>)}</div><button className="secondary" onClick={()=>setDate(today)}>Hoy</button></div><p className="muted">{pretty(start)} {end!==start?"— "+pretty(end):""}</p><div className={view==="Mes"?"calendar-grid":view==="Semana"?"week-grid":""}>{Array.from({length:Math.round((new Date(end).getTime()-new Date(start).getTime())/86400000)+1},(_,i)=>shift(start,i)).map(day=><section className="card agenda-day" key={day}><h3>{pretty(day)}</h3>{agenda.filter(x=>dayKey(x.starts_at)===day).map(appointmentRow)}{blocks.filter(x=>dayKey(x.starts_at)<=day&&dayKey(x.ends_at)>=day).map(x=><p className="block-label" key={x.id}>Bloqueado: {x.reason}</p>)}{!agenda.some(x=>dayKey(x.starts_at)===day)&&<p className="muted mini">Sin turnos</p>}</section>)}</div></>}
 {(tab==="Caja"||tab==="Historial")&&<><div className="toolbar">{["Hoy","Ayer","Semana","Mes","Anterior"].map(x=><button className="secondary" onClick={()=>period(x)} key={x}>{x}</button>)}</div>{filters}{tab==="Caja"&&<><div className="metrics"><Metric label="Hoy" value={money(todayP.total)}/><Metric label="Ayer" value={money(summarize(p,shift(today,-1),shift(today,-1)).total)}/><Metric label="Esta semana" value={money(summarize(p,shift(today,-((new Date(today+"T12:00:00Z").getUTCDay()+6)%7)),today).total)}/><Metric label="Este mes" value={money(monthP.total)}/><Metric label="Período seleccionado" value={money(range.total)} highlight/></div><div className="methods">{methods.map(m=><div className="card" key={m}><span className="muted">{m}</span><h3>{money(range.rows.filter(x=>x.method===m).reduce((s,x)=>s+Number(x.amount),0))}</h3></div>)}</div></>}<div className="card"><div className="toolbar"><input aria-label="Buscar cliente" placeholder="Buscar cliente…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Método de pago" value={method} onChange={e=>setMethod(e.target.value)}><option value="">Todos los medios</option>{methods.map(m=><option key={m}>{m}</option>)}</select></div>{paymentTable(filtered)}</div></>}
 {tab==="Clientes"&&<><input className="search" placeholder="Buscar por nombre o teléfono…" aria-label="Buscar cliente" value={search} onChange={e=>setSearch(e.target.value)}/><div className="card table-wrap"><table><thead><tr><th>Cliente</th><th>Teléfono</th><th>Primera visita</th><th>Última visita</th><th>Cortes</th><th>Total gastado</th></tr></thead><tbody>{c.filter(x=>(names[x.id]+" "+x.phone).toLowerCase().includes(search.toLowerCase())).map(x=>{const cuts=a.filter(y=>y.customer_id===x.id&&y.status==="Realizado").sort((a,b)=>a.starts_at.localeCompare(b.starts_at));return <tr key={x.id}><td><button className="text-button" onClick={()=>setCustomer(x)}>{names[x.id]}</button></td><td>{x.phone}</td><td>{cuts[0]?pretty(cuts[0].starts_at):"Sin visitas"}</td><td>{cuts.length?pretty(cuts[cuts.length-1].starts_at):"—"}</td><td>{cuts.length}</td><td>{money(p.filter(y=>y.customer_id===x.id).reduce((s,y)=>s+Number(y.amount),0))}</td></tr>;})}</tbody></table>{!c.length&&<p className="empty muted">Los clientes aparecen al recibir la primera reserva.</p>}</div></>}
 {tab==="Estadísticas"&&<>{filters}<p className="muted mini">Ingresos y cortes agrupados por fecha de cobro. Horarios y días solicitados incluyen reservas no canceladas.</p><div className="charts"><Chart title="Dinero generado por día" rows={group(range.rows,x=>dayKey(x.paid_at),x=>Number(x.amount))} currency/><Chart title="Facturación y comparación mensual" rows={group(range.rows,x=>dayKey(x.paid_at).slice(0,7),x=>Number(x.amount))} currency/><Chart title="Cortes diarios" rows={group(range.rows,x=>dayKey(x.paid_at),()=>1)}/><Chart title="Cortes mensuales" rows={group(range.rows,x=>dayKey(x.paid_at).slice(0,7),()=>1)}/><Chart title="Días con más trabajo" rows={days.map((label,i)=>({label,value:a.filter(x=>x.status==="Realizado"&&dayKey(x.starts_at)>=from&&dayKey(x.starts_at)<=to&&new Date(dayKey(x.starts_at)+"T12:00:00Z").getUTCDay()===i).length}))}/><Chart title="Horarios más solicitados" rows={Object.entries(a.filter(x=>x.status!=="Cancelado"&&dayKey(x.starts_at)>=from&&dayKey(x.starts_at)<=to).reduce<Record<string,number>>((o,x)=>{const k=time(x.starts_at);o[k]=(o[k]??0)+1;return o;},{})).sort(([a],[b])=>a.localeCompare(b)).map(([label,value])=>({label,value}))}/><Chart title="Medios de pago más utilizados" rows={group(range.rows,x=>x.method,()=>1)}/><Chart title="Clientes más frecuentes" rows={group(range.rows,x=>x.customer_id,()=>1).sort((a,b)=>b.value-a.value).slice(0,10).map(x=>({...x,label:names[x.label]??"Cliente"}))}/></div></>}
 {tab==="Notificaciones"&&<><div className="toolbar"><p className="muted">Se actualizan cada 15 segundos mientras el panel está abierto.</p><button disabled={busy||!unread} onClick={()=>void action("read")}>Marcar todas como leídas</button></div>{n.sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(x=><button key={x.id} className={"card notification "+(!x.read_at?"unread":"")} onClick={()=>setSelected(a.find(y=>y.id===x.appointment_id)??null)}><Bell/><div><p className="eyebrow">NUEVO TURNO {!x.read_at&&"· SIN LEER"}</p><h3>{x.payload.name}</h3><p>{pretty(x.payload.starts_at)} · {time(x.payload.starts_at)} · Corte: {money(x.payload.price)}</p><p className="muted">Teléfono: {x.payload.phone}</p></div><ArrowUpRight/></button>)}{!n.length&&<div className="card empty">Acá vas a recibir tus nuevas reservas.</div>}</>}
 {tab==="Configuración"&&<Configuration settings={settings} hours={hours} blocks={blocks} action={action} busy={busy}/>}
 </>}
 </main></div>{selected&&<AppointmentDialog appointment={selected} name={names[selected.customer_id]} phone={c.find(x=>x.id===selected.customer_id)?.phone??""} busy={busy} action={action} close={()=>setSelected(null)}/>}
 {customer&&<dialog open className="modal"><div className="modal-heading"><h2>{names[customer.id]}</h2><button className="secondary" onClick={()=>setCustomer(null)}>Cerrar</button></div><p>{customer.phone}</p><h3>Historial de turnos</h3>{a.filter(x=>x.customer_id===customer.id).sort((a,b)=>b.starts_at.localeCompare(a.starts_at)).map(x=><p key={x.id}>{pretty(x.starts_at)} · {time(x.starts_at)} · {x.status} · {money(x.price)}</p>)}</dialog>}</div>;
}
function Metric({label,value,highlight=false}:{label:string;value:string|number;highlight?:boolean}){return <div className={"metric "+(highlight?"highlight":"")}><span>{label}</span><strong>{value}</strong></div>}
function AppointmentDialog({appointment:a,name,phone,busy,action,close}:{appointment:Appointment;name:string;phone:string;busy:boolean;action:(a:string,d:Record<string,unknown>)=>Promise<boolean>;close:()=>void}){
 const [price,setPrice]=useState(String(a.price)),[method,setMethod]=useState(""),[date,setDate]=useState(dayKey(a.starts_at)),[slot,setSlot]=useState(""),[slots,setSlots]=useState<string[]>([]),[error,setError]=useState("");
 useEffect(()=>{let active=true;setSlot("");rpc<{starts_at:string}[]>("available_slots",{p_day:date}).then(x=>{if(active)setSlots(x.map(y=>y.starts_at));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[date]);
 async function save(type:string,data:Record<string,unknown>){if(await action(type,{id:a.id,...data}))close();else setError("No se pudo guardar. Revisá el mensaje en el panel.");}
 const closed=["Realizado","Cancelado","Ausente"].includes(a.status);
 return <dialog open aria-label="Gestionar turno" className="modal"><div className="modal-heading"><h2>{name}</h2><button disabled={busy} className="secondary" onClick={close}>Cerrar</button></div><p>{pretty(a.starts_at)} · {time(a.starts_at)} · {a.status}</p><p className="muted">Teléfono: {phone}</p><p className="mini muted">ID: {a.id}</p>{closed?<p>Turno cerrado. Se conserva el historial.</p>:<><div className="form-grid"><label>Precio ($)<input type="number" min="0" step=".01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Medio de pago<select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Seleccioná un medio</option>{methods.map(x=><option key={x}>{x}</option>)}</select></label></div><button className="wide" disabled={busy||!method||price===""||Number(price)<0||new Date(a.starts_at)>new Date()} onClick={()=>void save("complete",{price:Number(price),method})}>Realizado / Cobrado · {money(Number(price))}</button><p className="mini muted">El cobro se registra una sola vez y se conserva en Caja. Los turnos futuros no se pueden cobrar.</p><div className="actions wrap"><button className="secondary" disabled={busy||price===""||Number(price)<0} onClick={()=>void save("price",{price:Number(price)})}>Guardar precio</button>{["Confirmado","Cancelado","Ausente"].map(x=><button className="secondary" key={x} disabled={busy} onClick={()=>void save("status",{status:x})}>{x==="Confirmado"?"Confirmar":x==="Cancelado"?"Cancelar turno":"Marcar ausente"}</button>)}</div><hr/><h3>Reprogramar</h3><input aria-label="Nueva fecha" type="date" min={dayKey()} value={date} onChange={e=>setDate(e.target.value)}/><div className="slots">{slots.map(x=><button className={x===slot?"":"secondary"} key={x} onClick={()=>setSlot(x)}>{time(x)}</button>)}</div><button disabled={!slot||busy} onClick={()=>void save("reschedule",{starts_at:slot})}>Guardar nueva fecha y hora</button></>}{error&&<p className="alert" role="alert">{error}</p>}</dialog>;
}
function Configuration({settings,hours,blocks,action,busy}:{settings:Settings;hours:Hours[];blocks:Block[];action:(a:string,d:Record<string,unknown>)=>Promise<boolean>;busy:boolean}){
 const [s,setS]=useState(settings),[h,setH]=useState(hours),[error,setError]=useState("");
 async function upload(file:File|undefined,logo:boolean){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>800000){setError("Usá JPG, PNG o WebP de hasta 800 KB.");return;}const reader=new FileReader();reader.onload=()=>{const url=String(reader.result);setS(v=>logo?{...v,logo:url}:{...v,photos:[...v.photos,url].slice(0,6)});};reader.readAsDataURL(file);}
 return <div className="settings-grid"><form className="card" onSubmit={e=>{e.preventDefault();void action("settings",s);}}><h3>Tu peluquería</h3><label>Nombre<input value={s.name} required minLength={2} maxLength={100} onChange={e=>setS({...s,name:e.target.value})}/></label><label>Dirección<input required value={s.address} onChange={e=>setS({...s,address:e.target.value})}/></label><label>WhatsApp (código internacional y número)<input required pattern="[0-9]{10,15}" value={s.whatsapp} onChange={e=>setS({...s,whatsapp:e.target.value})}/></label><label>Instagram<input type="url" required value={s.instagram} onChange={e=>setS({...s,instagram:e.target.value})}/></label><div className="form-grid"><label>Precio del corte ($)<input type="number" required min={s.enabled?1:0} step=".01" value={s.price} onChange={e=>setS({...s,price:Number(e.target.value)})}/></label><label>Duración (minutos)<input type="number" required min="10" max="180" value={s.duration} onChange={e=>setS({...s,duration:Number(e.target.value)})}/></label></div><label>Logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0],true)}/></label><p className="mini muted">{s.logo?"Logo cargado. Guardá los cambios para publicarlo.":"Subí el logo original de TT Peluquería."}</p><label>Fotos del local y cortes (hasta 6)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0],false)}/></label>{s.photos.map((_,i)=><button key={i} className="secondary small" type="button" onClick={()=>setS({...s,photos:s.photos.filter((_,j)=>i!==j)})}>Quitar foto {i+1}</button>)}<label className="check"><input type="checkbox" checked={s.enabled} onChange={e=>setS({...s,enabled:e.target.checked})}/> Habilitar reservas online</label><p className="mini muted">Primero guardá los horarios de atención. Los cambios de precio y duración se aplican a nuevas reservas; las existentes conservan sus valores.</p><button disabled={busy}>Guardar configuración</button>{error&&<p className="alert">{error}</p>}</form>
 <div><form className="card" onSubmit={e=>{e.preventDefault();void action("hours",{hours:h});}}><h3>Horarios de atención</h3>{h.map((x,i)=><div className="hour-editor" key={x.id}><label className="check"><input type="checkbox" checked={!x.closed} onChange={e=>setH(h.map((v,j)=>j===i?{...v,closed:!e.target.checked}:v))}/>{days[x.id]}</label><input type="time" aria-label={"Apertura "+days[x.id]} required value={x.opens} disabled={x.closed} onChange={e=>setH(h.map((v,j)=>j===i?{...v,opens:e.target.value}:v))}/><input type="time" aria-label={"Cierre "+days[x.id]} required value={x.closes} disabled={x.closed} onChange={e=>setH(h.map((v,j)=>j===i?{...v,closes:e.target.value}:v))}/></div>)}<p className="mini muted">Hora de Argentina. Los turnos ya reservados permanecen en agenda si cambiás los horarios.</p><button disabled={busy}>Guardar horarios</button></form>
 <form className="card" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const d=new FormData(form);void action("block",{starts_at:String(d.get("start"))+":00-03:00",ends_at:String(d.get("end"))+":00-03:00",reason:d.get("reason")}).then(ok=>{if(ok)form.reset();});}}><h3>Bloquear un horario o varios días</h3><label>Desde<input name="start" type="datetime-local" required/></label><label>Hasta<input name="end" type="datetime-local" required/></label><label>Motivo<input name="reason" required maxLength={120} placeholder="Almuerzo, vacaciones, feriado…"/></label><button disabled={busy}><Plus size={17}/> Crear bloqueo</button><div>{blocks.map(x=><div className="block-item" key={x.id}><strong>{x.reason}</strong><p>{pretty(x.starts_at)} {time(x.starts_at)} — {pretty(x.ends_at)} {time(x.ends_at)}</p><button type="button" className="text-button" disabled={busy} onClick={()=>void action("unblock",{id:x.id})}>Quitar bloqueo</button></div>)}</div></form></div></div>;
}
